name: "Publish to Repo Action"
description: "GitHub Action that publishes artifacts to a repository."
author: siakhooi

branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  config-file:
    description: "The configuration file for the action."
    required: false
    default: "publish-to-repo.yml"
  token:
    description: "GitHub token with permissions to publish to the repository."
    required: true

outputs:
  commit_sha:
    description: "The SHA of the commit that was pushed."
    value: ${{ steps.publish.outputs.commit_sha }}
  committed:
    description: "Indicates whether a commit was made."
    value: ${{ steps.publish.outputs.committed }}
  changed_files_count:
    description: "Number of files that were changed in the commit."
    value: ${{ steps.publish.outputs.changed_files_count }}

runs:
  using: "composite"
  steps:
    - name: "Install yq"
      shell: bash
      run: |
        if ! command -v yq &> /dev/null; then
          echo "yq not found, installing..."
          sudo apt update && sudo apt install -y yq
        fi

    - name: "Run publish script"
      id: publish
      run: bash "$GITHUB_ACTION_PATH/publish-to-repo.sh" "${{ inputs.config-file }}" "${{ inputs.token }}"
      shell: bash
